[[redirects]]
  from = "/api/catalogo"
  to = "/.netlify/functions/catalogo"
  status = 200

[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."catalogo"]
  timeout = 30
